name: wash_in_time
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  bottom_bar: ^2.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter
  get: 4.6.5
  get_storage: ^2.0.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  lottie: ^1.4.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/63787-secure-login.json
